paywac/contracts/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, request
from flask_login import login_user, current_user, logout_user, login_required
from paywac import db, bcrypt
from paywac.contracts.forms import CreateContract, ButtonData, DeliverTo, ReviewAndDeploy, ShippingNumber
from paywac.contracts.utils import gwei_to_eth, deploy, secondsToText, wei_to_eth, get_deployment_price, gwei_to_wei, deploy_erc20
from paywac.models import Deployer, Oracle, User, Contracts_info, Button_data, Shipping_info, Contracts, Shipping_tracking, Gas_price
from uuid import uuid4
from crontab import CronTab
from datetime import datetime, timedelta
import os
import json

contracts = Blueprint('contracts', __name__)

@contracts.route('/contract/<string:address>')
def contract(address):
    """
    given a contract address it will display the details of the contract reading
    from the contract_info table
    """
    # get contract abi string
    with open('/home/andrea/Desktop/paywac_website_v02/paywac/static/contracts_code/build/paywac.json') as paywac_builded:
        data = json.load(paywac_builded)
    with open('/home/andrea/Desktop/paywac_website_v02/paywac/static/contracts_code/build/paywac_erc20.json') as paywac_erc20_builded:
        data_erc20 = json.load(paywac_erc20_builded)
    paywac_abi = data['abi']
    paywac_erc20_abi = data_erc20['abi'] 
    # data from the contracts deployed
    row = Contracts.query.filter_by(contract_address=address).first()

    uid = row.uuid
    contract_address = row.contract_address
    contract_title = row.title
    seller = row.seller_address
    price = row.item_price
    shipping_price = row.shipping_price
    status = row.status
    currency = row.buyer_address
    tracked = row.tracked

    # data from the contracts info
    row_info = Contracts_info.query.filter_by(contract_address=address).first()

    contract_start = row_info.contract_start
    contract_end = row_info.contract_end
    time_item_delivered = row_info.time_item_delivered
    has_buyer_paid = row_info.has_buyer_paid
    ranking = row_info.ranking
    latest_update = row_info.latest_update
    item_price = row_info.item_price
    shipping_price = row_info.shipping_price

    return render_template('contract.html', contract_start=contract_start, contract_end=contract_end, time_item_delivered=time_item_delivered,\
                            has_buyer_paid=has_buyer_paid, ranking=ranking, status=status, title=contract_title, contract_address=contract_address,\
                                latest_update=latest_update, item_price=item_price, shipping_price=shipping_price, currency=currency, tracked=tracked,\
                                    paywac_abi=paywac_abi, paywac_erc20_abi=paywac_erc20_abi)


# generate the html code for a button that will be embedded to a third party website to create a request for a new contract
@contracts.route('/intent/generate_button', methods=['GET', 'POST'])
@login_required
def create_button():
    """
    generate the html code for a button that will redirect the user to the contract request
    a form will be used to include specific info about the insertion
    """
    # generate uuid that will identify this button
    uuid = str(uuid4())

    # form that let the user insert the info

    form = ButtonData()

    # generate html for the button
    # the uuid will be the id that we will search in the table to retrieve all the data needed later
    if form.validate_on_submit():


        link =f"http://127.0.0.1:5000/intent/buy?uid={uuid}"

        button_html = f"""
        <a target="_blank" class="button" href="http://127.0.0.1:5000/intent/buy?uid={uuid}" data-size="large">
        <img src="../static/website_img/twitter.png" alt="" style="width:59px; height:24px;">
        </a>
        """

        # insert button data in the database
        row = Button_data(uuid=uuid, creator_mail=current_user.email, name=form.name.data, title=form.title.data, seller_address=form.seller_address.data, contract_time=form.contract_time.data,\
                            shipping_eta=form.shipping_eta.data, item_price=form.item_price.data, shipping_price=form.shipping_price.data, clicked=0,\
                            button_code=button_html, link=link, currency = form.currency.data)

        db.session.add(row)
        db.session.commit()

        return render_template('button_creation.html',display_form=False, form=form, generated_code=button_html, link=link)

    # LATER STEPS: when a request will be made we check for every value to match the insertion in the database, if
    # there will be a match we get the uuid and we create the request for the seller
    # if there is not a match it means that the data somehow got tampered and we do not create a new request

    return render_template('button_creation.html', display_form=True, form=form)

@contracts.route('/intent/buy', methods=['GET', 'POST'])
def buy():
    """
    collect data from buyer and create Shipping_info row and Contract row
    """
    uid = request.args.get('uid')
    # check if the uuid passed exists and check if the clicked field is set to False, if both this requirements are sadisfied we
    # and we can proceed to ask the user for the info that we need
    row = Button_data.query.filter_by(uuid=uid).first()
    if row != None and row.clicked == 0:
        
        creator_mail = row.creator_mail
        contract_time_formatted = secondsToText(row.contract_time)
        shipping_eta_formatted = secondsToText(row.shipping_eta)
        oracle_address = Oracle.query.filter(Oracle.active==1).first().id
        deployer_address = Deployer.query.filter(Deployer.active==1).first().id

        
        form = DeliverTo()
        # check if the currency for the payment will be ethere or theter
        if row.currency == 0:
            currency = "ETH"
            form.buyer_address.data = '0x0000000000000000000000000000000000000000'
            contract_type = 0
        else:
            currency = "USDT"
            contract_type = 1
            
        # confirmation, and creation of buy_request that the seller will review and accept(or that accepts automaticaly if setted to do so)
        if form.validate_on_submit() and row.clicked == 0:
            # add the shipping info binded to the uid to the database
            shipping_row = Shipping_info(uuid=uid, seller_email=creator_mail, buyer_email=form.email.data, street=form.street.data,\
                                            city=form.city.data, country=form.country.data, state=form.state.data, postal_code=form.postal_code.data,\
                                                buyer_name=form.name.data, buyer_surname=form.surname.data, buyer_address=form.buyer_address.data)
            # create new contract in pending seller approval status
            contract_row = Contracts(uuid=uid, name=row.name, title=row.title, owner=creator_mail, seller_address=row.seller_address,\
                                        oracle_address = oracle_address, deployer_address=deployer_address, contract_time=row.contract_time,\
                                            shipping_eta=row.shipping_eta, item_price=row.item_price, shipping_price=row.shipping_price, status=0,\
                                                buyer_address=form.buyer_address.data)

            row.clicked = 1
            db.session.add(row)
            db.session.add(shipping_row)
            db.session.add(contract_row)
            db.session.commit()
            
            # TODO send email here to buyer with info
            flash('Your request has been submitted successfully, please wait on your email for a notification with the payment info', 'success')
            # TODO send email notification to the seller
            return redirect(url_for('main.home'))
        return render_template('buy.html', response="info about the item", form=form, insertion_link=row.name, insertion_title=row.title,\
                                seller_address=row.seller_address, contract_time=contract_time_formatted, shipping_eta=shipping_eta_formatted,\
                                    item_price=row.item_price, shipping_price=row.shipping_price, currency=currency)
    elif row == None:
        flash("This request does not exists", 'danger')
        return redirect(url_for('main.home'))
    elif row.clicked == 1:
        flash("This request has already been done by somebody else already", 'warning')
        return redirect(url_for('main.home'))


#route that will allow the seller to review the complete info and decide if to accept and deploy the contract or not
@contracts.route("/intent/deploy_contract/<string:uid>", methods=['GET', 'POST'])
@login_required
def deploy_contract(uid):

    contract = Contracts.query.filter_by(uuid=uid).first()
    # check if the uuid exists
    if contract is None:
        flash(Nope, 'danger')
        return redirect(url_for('main.home'))
    ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"
    TOKEN_ADDRESS = "0x8ECEbbAc35822D2ddeAd001D5Bb4A8C2d49214F0"
    shipping_info = Shipping_info.query.filter_by(uuid=uid).first()
    contract_owner = contract.owner
    contract_status = contract.status
    contract_time = contract.contract_time
    contract_shipping_eta = contract.shipping_eta
    contract_item_price = contract.item_price
    contract_shipping_price = contract.shipping_price
    buyer_address = contract.buyer_address
    oracle = Oracle.query.filter(Oracle.active==1).first().address
    deployer = Deployer.query.filter(Deployer.active==1).first().address
    user_wac = User.query.filter_by(email=current_user.email).first()

    if current_user.email == contract_owner and contract_status == 0 and buyer_address == ZERO_ADDRESS:

        table_gas_price = Gas_price.query.filter_by(id=1).first()

        gas_price = table_gas_price.standard_gas_price
        contract_cost = table_gas_price.contract_cost

paywac/main/routes.py
from flask import render_template, request, Blueprint, redirect, url_for
from paywac import db

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html')


@main.route("/about")
def about():
    return render_template('about.html', title='About')


@main.route("/add_founds")
def add_founds():
    return render_template('add_founds_description.html', title='Add Founds')

# TODO to delete once we are not in dev
@main.route('/create_db')
def create_db():
    db.create_all()
    return redirect(url_for('main.home'))

paywac/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from paywac import db, bcrypt
from paywac.models import User, Gas_price, Contracts_types
from paywac.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from paywac.users.utils import save_picture, send_reset_email
from paywac.contracts.utils import wei_to_eth, gwei_to_eth
from math import floor

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.add_founds.data = current_user.recharge_address

    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)

    add_founds_address = current_user.recharge_address
    table_gas_price = Gas_price.query.filter_by(id=1).first()
    gas_price = table_gas_price.standard_gas_price
    contract_cost = Contracts_types.query.filter_by(id=1).first().gas_needed_for_deployment
    contract_erc20_cost = Contracts_types.query.filter_by(id=2).first().gas_needed_for_deployment
    user_avaiable_eth = wei_to_eth(current_user.wac_credits)

    eth_needed_for_deployment = gwei_to_eth(gas_price * contract_cost)
    eth_needed_for_erc20_deployment = gwei_to_eth(gas_price * contract_erc20_cost)

    deployments_avaiables = user_avaiable_eth / eth_needed_for_deployment
    deployments_erc20_avaiables = user_avaiable_eth / eth_needed_for_erc20_deployment

    return render_template('account.html', title='Account',
                           image_file=image_file, form=form, add_founds=add_founds_address, user_avaiable_eth=user_avaiable_eth,\
                                deployments_avaiables=floor(deployments_avaiables), deployments_erc20_avaiables=floor(deployments_erc20_avaiables),\
                                    gas_price = gas_price)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

paywac/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

paywac/templates/add_founds_description.html
{% extends "layout.html" %}
{% block content %}
Here i make an infographic on how to add tokens
{% endblock content %}

paywac/templates/buy.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
<div class="dropdown">
    <button class="btn btn-outline-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Item info
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% if insertion_link != ''%}
            <a class="dropdown-item" href="https://{{insertion_link}}">Insertion Link: {{ insertion_link }}</a>
        {% endif %}
        <a class="dropdown-item" href="#">Insertion Title: {{ insertion_title }}</a>
        <a class="dropdown-item" href="#">Seller Address: {{ seller_address }}</a>
        <a class="dropdown-item" href="#">Contract Time(time that you have to make the payment): {{ contract_time }}</a>
        <a class="dropdown-item" href="#">Shipping Time(start after you make the payment): {{ shipping_eta }}</a>
        <a class="dropdown-item" href="#">Item Price: {{ item_price }}</a>
        <a class="dropdown-item" href="#">Shipping Price: {{ shipping_price }}</a>
        <a class="dropdown-item" href="#">Currency: {{ currency }}</a>
        <a class="dropdown-item" href="#">Total Price To Pay: {{ shipping_price + item_price}}</a>
    </div>
</div>
    <form method="POST" action="">
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add your shipping info</legend>
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.surname.label(class="form-control-label") }}
                {% if form.surname.errors %}
                    {{ form.surname(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.surname.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.surname(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.street.label(class="form-control-label") }}
                {% if form.street.errors %}
                    {{ form.street(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.street.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.street(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.city.label(class="form-control-label") }}
                {% if form.city.errors %}
                    {{ form.city(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.city.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.city(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.country.label(class="form-control-label") }}
                {% if form.country.errors %}
                    {{ form.country(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.country.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.country(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.state.label(class="form-control-label") }}
                {% if form.state.errors %}
                    {{ form.state(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.state.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.state(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.postal_code.label(class="form-control-label") }}
                {% if form.postal_code.errors %}
                    {{ form.postal_code(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.postal_code.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.postal_code(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            {% if currency == "USDT" %}
            <div class="form-group">
                {{ form.buyer_address.label(class="form-control-label") }}
                {% if form.buyer_address.errors %}
                    {{ form.buyer_address(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.buyer_address.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.buyer_address(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            {% else %}
            <div class="form-group">
                {{ form.buyer_address(type="hidden") }}
            </div>
            {% endif %}
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.confirm.label(class="form-control-label") }}
                {% if form.confirm.errors %}
                    {{ form.confirm(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group text-right">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock content %}

paywac/templates/home.html
{% extends "layout.html" %}
{% block content %}
Description of the service with images ecc
{% endblock content %}

paywac/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>PayWac - {{ title }}</title>
    {% else %}
        <title>PayWac</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar-custom navbar-expand-md navbar-dark bg-steel fixed-top py-1">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">PayWac</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('contracts.create_button') }}">New Button</a>
              <a class="nav-item nav-link" href="{{ url_for('main.add_founds') }}">Add Ethereum</a>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                  More
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{{ url_for('contracts.my_contracts') }}">Search Contracts</a>
                </div>
              </li>
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">New Contract</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">Search Contracts</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                    My stuff
                  </a>
                  <div class="dropdown-menu">
                      <a class="dropdown-item" href="{{ url_for('contracts.my_contracts') }}">My Contracts</a>
                      <a class="dropdown-item" href="{{ url_for('contracts.my_buttons') }}">My Buttons</a>
                  </div>
                </li>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row justify-content-md-center">
        <div class="col col-lg"></div>
        <div class="col-md-auto">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col col-lg"></div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

paywac/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}